---
# plays that make centos and rhel act or look
# like an ubuntu system for ease of testing

- name: Make raid/smart scripts work.
  file:
    state: link
    src: /sbin/lspci
    dest: /usr/bin/lspci
    force: yes

- name: Create FStest ubuntu directory.
  file:
    state: directory
    dest: /usr/lib/ltp/testcases/bin

- name: Make fsstress same path as ubuntu.
  file:
    state: link
    src: /usr/bin/fsstress
    dest: /usr/lib/ltp/testcases/bin/fsstress
    force: yes

# iozone install tasks
- name: Download tar file
  get_url:
    url: "https://www.iozone.org/src/current/iozone3_508.tar"
    dest: "/tmp/iozone.tar"

- name: Extract tar file
  unarchive:
    src: "/tmp/iozone.tar"
    dest: "/tmp/"
    remote_src: yes

- name: Change to the extracted directory and run make
  command: "make linuxpowerpc64"
  args:
    chdir: "/tmp/iozone"

- name: Copy output to a directory in PATH
  command: cp /tmp/iozone/iozone /usr/local/bin/
  args:
    removes: "/usr/local/bin/output"

- name: Change permissions of the binary
  file:
    path: "/usr/local/bin/iozone"
    mode: '0755'
