---
- name: Create the sudo group.
  group:
    name: sudo
    state: present
  tags:
   - user

- name: Create the ansible user.
  user:
    name: "{{ cm_user }}"
    groups: sudo
    shell: /bin/bash
    uid: "{{ cm_user_uid }}"
    update_password: on_create
  when: cm_user is defined and cm_user_uid is defined
  register: user_created
  tags:
   - user

- name: Delete the ansible users password.
  command: "passwd -d {{ cm_user }}"
  when: user_created is defined and user_created is changed
  tags:
   - user

- name: Ensure includedir is present in sudoers.
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: visudo -cf %s
  tags:
    - sudoers
    - user

- name: Create the cephlab_sudo sudoers.d file.
  template:
    src: cephlab_sudo
    dest: /etc/sudoers.d/cephlab_sudo
    owner: root
    group: root
    mode: 0440
    validate: visudo -cf %s
  tags:
    - sudoers
    - user

- name: Add authorized keys for the ansible user.
  ansible.posix.authorized_key: 
    user: "{{ cm_user }}"
    key: "{{ cm_user_ssh_keys|join('\n') }}"
    exclusive: True
  when: cm_user_ssh_keys is defined and
        cm_user is defined
  tags:
    - pubkeys
